include ../defines.mk

TEST_NAME = word_count
TEST_FILES = word_count sort
#TEST_ARGS = ../../datasets/word_count/word_100MB.txt
TEST_ARGS = $(DATASET_HOME)/word_count/word_1000MB.txt $(NCORES)

include $(HOME)/Default.mk

